# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: array_attribute 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "array_attribute"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["kazuyoshi tlacaelel"]
  s.date = "2014-06-02"
  s.description = "This helper creates two methods to classes.\n\narray_attribute and carray_attribute.\n\nWith these you can create methods that encapsulate an array\nproperty if you have never used or accessed the property it will\nhave an empty array as a default value.\n  "
  s.email = "kazu.dev@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/array_attribute.rb",
    "test/helper.rb",
    "test/test_array_attribute.rb"
  ]
  s.homepage = "http://github.com/ktlacaelel/array_attribute"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Array Attribute - Array atrribute accessor helper."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
    else
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
  end
end

